@startuml AST of ../examples/barebone/basic-2.fog
title AST of ../examples/barebone/basic-2.fog
skinparam nodesep 30
skinparam ranksep 20
rectangle "Program" as n0 #e5e5e5
rectangle ":" as n1 #c2fff2
rectangle "a" as n2 #fffdd0
rectangle "Float32" as n3 #fffdd0
n1 <-- n2
n1 <-- n3
n0 <-- n1
rectangle "=" as n4 #c2fff2
rectangle "a" as n5 #fffdd0
rectangle "-" as n6 #cbe9ff
rectangle "+" as n7 #cbe9ff
rectangle "+" as n8 #cbe9ff
rectangle "4" as n9 #ffcece
n8 <-- n9
rectangle "/" as n10 #cbe9ff
rectangle "3" as n11 #ffcece
n10 <-- n11
rectangle "2" as n12 #ffcece
n10 <-- n12
n8 <-- n10
n7 <-- n8
rectangle "*" as n13 #cbe9ff
rectangle "2" as n14 #ffcece
n13 <-- n14
rectangle "-" as n15 #cbe9ff
rectangle "+" as n16 #cbe9ff
rectangle "-" as n17 #cbe9ff
rectangle "1" as n18 #ffcece
n17 <-- n18
n16 <-- n17
rectangle "/" as n19 #cbe9ff
rectangle "6" as n20 #ffcece
n19 <-- n20
rectangle "3" as n21 #ffcece
n19 <-- n21
n16 <-- n19
n15 <-- n16
rectangle "9" as n22 #ffcece
n15 <-- n22
n13 <-- n15
n7 <-- n13
n6 <-- n7
rectangle "-" as n23 #cbe9ff
rectangle "1" as n24 #ffcece
n23 <-- n24
n6 <-- n23
n4 <-- n5
n4 <-- n6
n0 <-- n4
@enduml
