@startuml AST of ../examples/barebone/basic-1.fog
title AST of ../examples/barebone/basic-1.fog
rectangle "Program" as n0 #e5e5e5
rectangle ":" as n1 #c2fff2
rectangle "num" as n2 #fffdd0
rectangle "Int32" as n3 #fffdd0
n1 <-- n2
n1 <-- n3
n0 <-- n1
rectangle "=" as n4 #c2fff2
rectangle "num" as n5 #fffdd0
rectangle "5" as n6 #ffcece
n4 <-- n5
n4 <-- n6
n0 <-- n4
@enduml
