@startuml AST of ../examples/barebone/basic-3.fog
title AST of ../examples/barebone/basic-3.fog
skinparam nodesep 30
skinparam ranksep 20
rectangle "Program" as n0 #e5e5e5
rectangle ":" as n1 #c2fff2
rectangle "f" as n2 #fffdd0
rectangle "->" as n3 #cbe9ff
rectangle "Int32" as n4 #fffdd0
n3 <-- n4
rectangle "Int32" as n5 #fffdd0
n3 <-- n5
n1 <-- n2
n1 <-- n3
n0 <-- n1
rectangle "=" as n6 #c2fff2
rectangle "f" as n7 #fffdd0
rectangle "λ" as n8 #ffc9fc
rectangle "x" as n9 #fffdd0
rectangle "+" as n10 #cbe9ff
rectangle "x" as n11 #fffdd0
n10 <-- n11
rectangle "2" as n12 #ffcece
n10 <-- n12
n8 <-- n9
n8 <-- n10
n6 <-- n7
n6 <-- n8
n0 <-- n6
rectangle ":" as n13 #c2fff2
rectangle "num1" as n14 #fffdd0
rectangle "Int32" as n15 #fffdd0
n13 <-- n14
n13 <-- n15
n0 <-- n13
rectangle "=" as n16 #c2fff2
rectangle "num1" as n17 #fffdd0
rectangle "f" as n18 #cbe9ff
rectangle "67" as n19 #ffcece
n18 <-- n19
n16 <-- n17
n16 <-- n18
n0 <-- n16
@enduml
