@startebnf AST Parser

title AST Parser (no sugars)

(* Top level *)

program = {type_annotation | declaration}-;

type_annotation = identifier, ":", expr;

declaration = identifier, "=", expr;

(* Expressions *)

expr =
    identifier
  | literal
  | lambda
  | expr_unary
  | expr_binary;

lambda = (identifier | type_annotation), "=>", expr;

expr_unary = unary_op, expr;

expr_binary = expr, binary_op, expr;

tuple = "(", [expr, {"," ,expr}, [","]], ")";


@endebnf